# Q1: Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name, experience_required. You have to scrape first 10 jobs data.

In [1]:
import selenium
import pandas as pd
from selenium import webdriver

In [5]:
driver=webdriver.Chrome(r'C:\Users\Prsi\Desktop\ML\chromedriver.exe')

In [6]:
url="https://www.naukri.com/data-analyst-jobs-in-bangalore?k=data%20analyst&l=bangalore"

In [7]:
driver.get(url)

In [8]:
job=[]
company=[]
location=[]
experience=[]

In [9]:
title=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
title[0:10]

[<selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="95239c96-a6a3-40f9-b9bb-76a0aadc9ac7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="29894751-42a9-489b-a55d-68c5e9a77d6d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="09efafa6-d098-4f97-a1ef-c6be27f9efb8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="5dd89ac8-2439-4e77-a80c-b4663e5fb7c9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="e0c7cb1e-8a2a-4948-8838-9843e6381622")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="a64f98cf-aec4-4056-a7ca-bfd776024113")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="b54962b9-b8af-4309-a328-e514e7d59a6f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="149e8d7a-070c-41f3-8f3f-d875177019ca")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="8769875b-882c-4d13-8aa0-00dd2049508b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="e27f92f5-24d1-4eb6-ac4e-fd5fa022ee54")>]

In [10]:
for i in title:
    t=i.text
    job.append(t)
    
job[0:10]

['Data Scientist / Data Analyst -Business Analyst',
 'Data Analyst - Informatica MDM',
 'Assistant Vice President - MIS & Reporting ( Business Data Analyst)',
 'Data Analyst',
 'Hiring For Data Analyst/ MIS Reporting Analyst - Bangalore',
 'Consultant-Data Analyst -Bangalore',
 'Data analyst - Google Analytics',
 'Senior/Regular Business Analyst / Data Analyst',
 'SW Technologist I- Data Analyst',
 'Data Analyst']

In [11]:
companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
companies_tags[0:10]

[<selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="7647e02d-50c6-4762-8c78-70f61e57694e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="00313846-fc20-4874-ae0d-2a60adecaca8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="ba9f800f-dadc-414a-88b0-592d69e17145")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="e7f43407-9ae9-4570-9f95-d5713908b6fe")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="aea2abdd-c492-4610-a766-4b67abd31a8d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="78ebf05d-621d-4da7-9409-cb8a89c1f6f0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="2f3cc3df-321e-44e2-954f-e466b01fb270")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="9019bae6-bc93-4999-9434-096cf2698962")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="0eecf7ac-1d40-4302-b75c-ce76bf5c0b41")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="f90afb29-2440-4448-8b3a-0d890e6a49bd")>]

In [12]:
for i in companies_tags:
    company_name=i.text
    company.append(company_name)

company[0:10]

['Inflexion Analytix Private Limited',
 'Shell India Markets Private Limited',
 'INTERTRUSTVITEOS CORPORATE AND FUND SERVICES PVT. LTD.',
 'SA Tech Software (I) Pvt. Ltd.',
 'PHARMACEUTICAL RESEARCH ASSOCIATES INDIA Pvt Ltd',
 'Innovsource Services Private Limited',
 'H and M Hennes and Mauritz (P) Ltd.',
 'Luxoft',
 'Philips India Limited',
 'Flipkart Internet Private Limited']

In [13]:
e=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span[1]")
e[0:10]

[<selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="a8b807b2-7b2b-41cb-a367-4d8351266a6b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="ce4bfb4d-b951-4d8c-af41-b97d63698a6a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="ccfedc2a-8017-4951-a664-193fea08b10a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="9f8bcbd1-36a5-403e-9d3a-d59234ffb479")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="b21dbf6c-02cb-4db5-95a6-7274aa62db08")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="e2762434-6033-4d59-9eda-b82dc94a2c6f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="9a5cfb1f-df27-4ddc-8f21-3f9110f39aca")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="eb0db26d-ea2b-46c3-9815-11ee56e3a8b9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="1732c7fc-c941-4d23-9a31-0b5ff50af0ae")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="bcad9e95-f7f4-494e-ac0a-1c28a58195cc")>]

In [14]:
for i in e:
    ex=i.text
    experience.append(ex)

experience[0:10]

['0-3 Yrs',
 '6-9 Yrs',
 '12-18 Yrs',
 '1-3 Yrs',
 '2-4 Yrs',
 '2-7 Yrs',
 '4-7 Yrs',
 '3-6 Yrs',
 '5-10 Yrs',
 '1-3 Yrs']

In [15]:

l=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
l[0:10]

[<selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="0963f1fb-9e3c-42d4-a3b1-690ab54671e5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="74699e32-c944-42d0-b6b1-a5ce3e1ae2d3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="9fbd2d89-1e48-440f-b392-a9acde4d2687")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="f8502086-3c7d-4707-b489-e5f089e4fe46")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="aa5911bf-4481-4564-a9f2-eb4d57290238")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="39678d3a-a9d3-4a92-8431-974920d37fdc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="8edaf155-59b8-47e7-8925-aa6cc549c147")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="5839604c-fadd-44b9-a881-6bc472bf8529")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="e828b8fa-5c37-481d-9cea-6a3c04b7c454")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71ad50e29f5e37dca3c689e80220f02e", element="77fbc5ed-1ddc-4eaf-8dfa-42902d6012c8")>]

In [16]:
for i in l:
    ex=i.text
    location.append(ex)

location[0:10]

['Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram, Chennai, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Mumbai, Bangalore/Bengaluru',
 'Kolkata, Pune, Chennai, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru']

In [17]:
df=pd.DataFrame({"job":job[0:10],
                "location":location[0:10],
                "company":company[0:10],
                "experience":experience[0:10]})

In [18]:
df

,job,location,company,experience
0,Data Scientist / Data Analyst -Business Analyst,"Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/...",Inflexion Analytix Private Limited,0-3 Yrs
1,Data Analyst - Informatica MDM,Bangalore/Bengaluru,Shell India Markets Private Limited,6-9 Yrs
2,Assistant Vice President - MIS & Reporting ( B...,"Mumbai, Bangalore/Bengaluru",INTERTRUSTVITEOS CORPORATE AND FUND SERVICES P...,12-18 Yrs
3,Data Analyst,"Kolkata, Pune, Chennai, Bangalore/Bengaluru, D...",SA Tech Software (I) Pvt. Ltd.,1-3 Yrs
4,Hiring For Data Analyst/ MIS Reporting Analyst...,Bangalore/Bengaluru,PHARMACEUTICAL RESEARCH ASSOCIATES INDIA Pvt Ltd,2-4 Yrs
5,Consultant-Data Analyst -Bangalore,Bangalore/Bengaluru,Innovsource Services Private Limited,2-7 Yrs
6,Data analyst - Google Analytics,Bangalore/Bengaluru,H and M Hennes and Mauritz (P) Ltd.,4-7 Yrs
7,Senior/Regular Business Analyst / Data Analyst,Bangalore/Bengaluru,Luxoft,3-6 Yrs
8,SW Technologist I- Data Analyst,Bangalore/Bengaluru,Philips India Limited,5-10 Yrs
9,Data Analyst,Bangalore/Bengaluru,Flipkart Internet Private Limited,1-3 Yrs

In [19]:
driver.close()

# Q2: Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name, full job-description. You have to scrape first 10 jobs data.

In [38]:
driver=webdriver.Chrome(r'C:\Users\Prsi\Desktop\ML\chromedriver.exe')

In [39]:
driver.get("https://www.naukri.com/")

In [40]:
# entering “Data Scientist” in “Skill,Designations,Companies” field 
search_field_designation=driver.find_element_by_id("qsb-keyword-sugg")

search_field_designation.send_keys("Data Scientist")

In [41]:
# clicking the search button
search_button=driver.find_element_by_xpath("//div[@class='search-btn']/button")
search_button.click()

In [55]:
# creating empty lists for scraping data
job_title=[]
job_location=[]
company_name=[]
description=[]

In [49]:
title=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
title[0:10]

[<selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="cb4c2383-cd69-49b1-bfc7-e601d88de555")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="51e7d84b-8610-45ef-b42b-3e489837886b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="126185cd-2bc1-4bdd-8aaa-73f175f8c28f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="4ebc390e-e641-422a-a0ae-ab395a893dd2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="f3e60cd0-a742-4365-a9df-cda9bf2f8e14")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="68ab0b2e-9f54-4d5f-a56c-2011c043909b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="b7940729-e7ec-4805-b5c1-bcf63d22694d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="40d0c203-3afa-4b94-838e-77c070224c0e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="3d03340e-5980-45a5-9590-776e080264f3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="6032d5ef-c49e-4ed2-ae95-71967fa4c5ad")>]

In [50]:
for i in title:
    t=i.text
    job.append(t)
    
job[0:10]

['Data Scientist / Data Analyst -Business Analyst',
 'Data Scientist',
 'Big Data - Data Scientist',
 'Specialist I - Data Scientist',
 'Lead Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'SDE Lead Data Scientist-L3',
 'Computational Design Lead Data Scientist-L3',
 'Hiring For DATA Scientist - ON Contract Basis (3-6 Months)']

In [51]:
companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
companies_tags[0:10]

[<selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="c7560d70-6770-4728-8e41-867f0cc70f64")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="27871bc5-754d-4268-b42a-2475640f7564")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="9a3ead28-fe5d-42b5-9ca5-0838b489cf28")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="4ac47fd6-6edf-4250-be1e-d944d7222ccf")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="00d68266-632e-495b-92fb-bbb1a639c16c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="83379220-6380-4ec8-a3da-f1c780bc96cd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="599eff5b-ffdc-4111-a9e1-6c4d27976617")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="26f28b3d-0180-4e38-ac0f-f780d0909718")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="b8c02e3e-bb50-4cc5-8087-dfc39cabfc0f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="0c2af050-1b4a-4ba7-98d2-ca3b74139457")>]

In [52]:
for i in companies_tags:
    company_name=i.text
    company.append(company_name)

company[0:10]

['Inflexion Analytix Private Limited',
 'Wipro Limited',
 'Xoriant Solutions Pvt Ltd',
 'Philips India Limited',
 'Intel Technology India Pvt Ltd',
 'Oracle India Pvt. Ltd.',
 'IBM India Pvt. Limited',
 'Huawei Technologies India Pvt Ltd',
 'Huawei Technologies India Pvt Ltd',
 'GlobalEdx Learning and Technology Solution Pvt Ltd']

In [53]:

head=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
for i in head:
    print(i.text)
    job.append(i.text)

Data Scientist / Data Analyst -Business Analyst
Data Engineer/Data Scientist/Data Analysis
Data Engineer/Data Scientist/Data Analysis
Acon / Con - Data Scientist
Data Scientist
Data Scientist
Specialist I - Data Scientist
Data Scientist
Lead Data Scientist
Data Scientist
SDE Lead Data Scientist-L3
Computational Design Lead Data Scientist-L3
Data Scientist - IBM Garage
Data Scientist
Data Scientist
Big Data - Data Scientist
Data Scientist
Hiring For Lead data Scientist For Bangalore location
Principal Data Scientist
we are hiring For the role of data engineer\data scientist

In [54]:

des_url=[]
for i in head:
    print(i.get_attribute('href'))
    des_url.append(i.get_attribute('href'))

https://www.naukri.com/job-listings-data-scientist-data-analyst-business-analyst-inflexion-analytix-private-limited-mumbai-hyderabad-secunderabad-pune-gurgaon-gurugram-chennai-bangalore-bengaluru-0-to-3-years-100521000368?src=jobsearchDesk&sid=16216595935325362_3&xp=1&px=1
https://www.naukri.com/job-listings-data-engineer-data-scientist-data-analysis-niftel-communications-private-limited-noida-chandigarh-indore-gurgaon-gurugram-ahmedabad-jaipur-bangalore-bengaluru-delhi-ncr-mumbai-all-areas-3-to-8-years-200521604259?src=jobsearchDesk&sid=16216595935325362_3&xp=2&px=1
https://www.naukri.com/job-listings-data-engineer-data-scientist-data-analysis-niftel-communications-private-limited-noida-chandigarh-indore-gurgaon-gurugram-ahmedabad-jaipur-bangalore-bengaluru-delhi-ncr-mumbai-all-areas-3-to-8-years-200521004257?src=jobsearchDesk&sid=16216595935325362_3&xp=3&px=1
https://www.naukri.com/job-listings-acon-con-data-scientist-pylon-management-consulting-pvt-ltd-noida-gurgaon-gurugram-bangalore-bengaluru-2-to-6-years-090321002828?src=jobsearchDesk&sid=16216595935325362_3&xp=4&px=1
https://www.naukri.com/job-listings-data-scientist-techknowledgey-pte-ltd-bangalore-bengaluru-0-to-2-years-070521003138?src=jobsearchDesk&sid=16216595935325362_3&xp=5&px=1
https://www.naukri.com/job-listings-data-scientist-wipro-limited-kolkata-hyderabad-secunderabad-chennai-bangalore-bengaluru-4-to-9-years-210521000038?src=jobsearchDesk&sid=16216595935325362_3&xp=6&px=1
https://www.naukri.com/job-listings-specialist-i-data-scientist-philips-india-limited-bangalore-bengaluru-4-to-7-years-170521500993?src=jobsearchDesk&sid=16216595935325362_3&xp=7&px=1
https://www.naukri.com/job-listings-data-scientist-ibm-india-pvt-limited-bangalore-bengaluru-6-to-8-years-110521907352?src=jobsearchDesk&sid=16216595935325362_3&xp=8&px=1
https://www.naukri.com/job-listings-lead-data-scientist-intel-technology-india-pvt-ltd-bangalore-bengaluru-6-to-10-years-070521500578?src=jobsearchDesk&sid=16216595935325362_3&xp=9&px=1
https://www.naukri.com/job-listings-data-scientist-oracle-india-pvt-ltd-bangalore-bengaluru-6-to-10-years-190521008276?src=jobsearchDesk&sid=16216595935325362_3&xp=10&px=1
https://www.naukri.com/job-listings-sde-lead-data-scientist-l3-huawei-technologies-india-pvt-ltd-bangalore-bengaluru-5-to-8-years-120521901434?src=jobsearchDesk&sid=16216595935325362_3&xp=11&px=1
https://www.naukri.com/job-listings-computational-design-lead-data-scientist-l3-huawei-technologies-india-pvt-ltd-bangalore-bengaluru-5-to-8-years-120521901329?src=jobsearchDesk&sid=16216595935325362_3&xp=12&px=1
https://www.naukri.com/job-listings-data-scientist-ibm-garage-ibm-india-pvt-limited-noida-hyderabad-secunderabad-bangalore-bengaluru-5-to-8-years-040521900448?src=jobsearchDesk&sid=16216595935325362_3&xp=13&px=1
https://www.naukri.com/job-listings-data-scientist-ibm-india-pvt-limited-noida-hyderabad-secunderabad-bangalore-bengaluru-4-to-9-years-300421904650?src=jobsearchDesk&sid=16216595935325362_3&xp=14&px=1
https://www.naukri.com/job-listings-data-scientist-ibm-india-pvt-limited-noida-hyderabad-secunderabad-bangalore-bengaluru-5-to-8-years-030521900421?src=jobsearchDesk&sid=16216595935325362_3&xp=15&px=1
https://www.naukri.com/job-listings-big-data-data-scientist-xoriant-solutions-pvt-ltd-kochi-cochin-indore-hyderabad-secunderabad-pune-ahmedabad-bangalore-bengaluru-mumbai-all-areas-1-to-3-years-130521005018?src=jobsearchDesk&sid=16216595935325362_3&xp=16&px=1
https://www.naukri.com/job-listings-data-scientist-applied-materials-india-private-limited-bangalore-bengaluru-2-to-4-years-070521901521?src=jobsearchDesk&sid=16216595935325362_3&xp=17&px=1
https://www.naukri.com/job-listings-hiring-for-lead-data-scientist-for-bangalore-location-societe-generale-global-solution-centre-pvt-ltd-bangalore-bengaluru-5-to-9-years-130521000901?src=jobsearchDesk&sid=16216595935325362_3&xp=18&px=1
https://www.naukri.com/job-listings-principal-data-scientist-netapp-india-private-limited-bangalore-bengaluru-10-to-15-years-070521906988?src=jobsearchDesk&sid=16216595935325362_3&xp=19&px=1
https://www.naukri.com/job-listings-we-are-hiring-for-the-role-of-data-engineer-data-scientist-collabera-technologies-private-limited-bangalore-bengaluru-5-to-8-years-170521006288?src=jobsearchDesk&sid=16216595935325362_3&xp=20&px=1

In [56]:
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException,ElementNotInteractableException
for i in des_url:
    driver.get(i)
    try:
        text=driver.find_element_by_xpath("//div[@class='dang-inner-html']").text
        description.append(text)
    except NoSuchElementException:
        description.append("no description")

In [57]:
description

["Job Role : Data Scientist/Data Analyst /Business Analyst\n\nLocation : Chennai/Bangalore/Hyderabad/Pune/Mumbai/Delhi\n\nGreetings from CAIA - Center for Artificial Intelligence & Advanced Analytics\n43% of companies experienced a high deficit of skilled resources with Advanced Analytical skills and AI implementing capabilities in year 2020. CAIA gives you a great opportunity to enter the world of future technologies and Innovations- Data Science, Analytics, AI, Data Visualization and Cloud Computing.\n\nWhile 2020 was a year like no other, we are living in an interesting times where data is reshaping the world, and businesses are rapidly adopting technology to gain an edge over others. Hence, there's a substantial increase in demand for technology professionals who can implement systems in data science, machine learning and AI in Tier 1 and Tier 2 organization's working closely with us.\n\nTo help you build a sustainable career we would like you to utilize data, software and Analytical approaches in Data Science and AI to up skill and get recruited into an organization appreciating your skilling journey.\nApplications invited from all Freshers and experienced candidates (0-3 yrs) aspiring to make a career in Artificial Intelligence and Advanced Analytics and Data Science.\nIf you wish to make a shift in your career or undergo a career transition, upskilling is essential since it allows you to learn more about the domain and acquire the required skills.\n\nCall to schedule interview Monday -Saturday from 10:00 am to 7Pm\n\nManigandan -+91 7299917200\n\nEmail : manigandan@centerforaia.com\n\nWhat is needed from you?\n\nFreshers who wish to start their career in Analytics and AI and professionals who wish to\nupskill or change their domain to analytics and emerging technologies are free to apply.\nAn Educational background in any one of the following- BE/B.Tech, ME/M Tech, MSc, BSc/MSc Maths and Statistics, B Com, BCA, BSc CS, BSC IT, MSC IT, MCA\nSkills relating to Mathematics/Statistics.\nNatural passion towards numbers, business, coding, Analytics and Artificial Intelligence, Machine Learning, visualization\nGood verbal and written communication skills\nAbility to understand domains in businesses across various sectors\n\n\nSelection procedure includes\n\nAptitude Test & Communication Exam - Online / Offline\nSQL/Python test - Online / Offline\n\nCandidates who clears the above will have one-one discussion with our Career Guidance Manager for further evaluation and processing of your Resume.\n\n\nAll the Shortlisted candidates will be eligible to continue the corporate training with CAIA\nWhat you can expect from us?\n\nYou will get trained on the following modules for a period of 12-14 weeks:\n\nSQL & PLSQL\nData Wrangling using Python\nData Visualization Using Power-BI\nStatistics for Machine Learning\nArtificial Intelligence, Data Interpretation\nSupervised & Unsupervised Learning,\nNLP & Deep Learning\nCloud Data Lake\nBusiness intelligence & Data Visualization\nSimulation Projects\nExpected Outcome?\n\nAt the end of the Training you are expected to be well versed with the following:\n\nAnalysis of large and complex data sets from multiple sources\nDevelopment and evaluation of data analytics models, algorithms and solutions\nUnderstanding/implementation of ML algorithms, performance tuning and reporting\nImplementation of algorithms to mine targeted data and the ability to convert data in to a business story\nTranslation of business requirements into technical requirements; Data extraction, preparation and transformation\nIdentification, development and implementation of statistical techniques and algorithms that address business challenges and adds value to the organization\nRequirement Analysis and communication of findings in the form of a meaningful story with the stakeholders\nFinding analytical solutions to abstract business issues.\nApply objective analysis of facts before coming to a conclusion\n\nAbout CAIA - Inflexion Analytix Private Limited\n\nCenter for Artificial Intelligence and Advanced Analytics (Center for AIA) is the brainchild of experienced and visionary alumni of IIT Madras and Bombay.\nDigital leaders - 5F World and Systech Solutions have joined hands to create a venture for architecting the future of society, workforce, governments and businesses. 5F World specializes in designing solutions around digital platforms and Systech Solutions has an expertise in architecting Artificial Intelligence and Advance Analytics solutions for Fortune 500 companies.\nOur Website : http://www.centerforaia.com/\n\nhttps://inflexion-analytix-private-limited.business.site/?m=true\n\nCenter for Artificial Intelligence & Advanced Analytics (CAIA) focuses on the following:\n\n1. Global Research on emerging trends, technologies and applications in AI and Advanced Analytics\n2. Advanced Training programs for readying the future ready workforce\n3. Solutions to herald the futuristic lifestyle and workspaces in the field of AI and Data Science.",
 'Roles and Responsibilities\nWe have Urgent Requirement for Data Scientist/ Data Engineer / Data Analysis for one of the top U.S based company in Gurugram Location .\n\nExperience Required- 2+ yrs\nSalary Package- 24 - 28 lpa\nLocation- Gurugram (Currently Work from Home)\nNotice Period - Immediate or 15 Days\n\nSkills Required :-\n\nAWS\nPYTHON\nSQL\nREST API\nSPARK\nPANDAS\nNLP\nJUPYTER\nREST\n\nInterested Candidates can share me their resume on karishma.suri@niftel.com or contact me on 6387398293',
 'Roles and Responsibilities\nWe have Urgent Requirement for Data Scientist/ Data Engineer / Data Analysis for one of the top U.S based company in Gurugram Location .\n\nExperience Required- 2+ yrs\nSalary Package- 24 - 28 lpa\nLocation- Gurugram (Currently Work from Home)\nNotice Period - Immediate or 15 Days\n\nSkills Required :-\n\nAWS\nPYTHON\nSQL\nREST API\nSPARK\nPANDAS\nNLP\nJUPYTER\nREST\n\nInterested Candidates can share me their resume on karishma.suri@niftel.com or contact me on 6387398293',
 '2-4 yrs - Job Location - Bangalore only\n\n4-6 yrs - Job Location - Gurgaon / Noida only\n\nQualification\nMasters or PhD in Computer Science, Statistics, Mathematics, Engineering, Bioinformatics, Physics, Operations Research, or related fields, with 2-6 years of relevant experience\nStrong mathematical background with ability to understand algorithms and methods from a mathematical viewpoint and an intuitive viewpoint.\n\nDesired Skills and Experience\nAbility to break down complex problems, and develop strategies to solve them\nTranslate business objectives into analytic approaches and identify data sources to support analysis.\nAnalyze and model structured data using advanced statistical methods\nPerform exploratory data analyses, generate and test working hypotheses, prepare and analyze historical data and identify patterns.\nAnalyze data using SAS, R, Python, open source packages and commercial/enterprise applications.\nPerform machine learning, Text analytics, and statistical analysis methods, such as classification, collaborative filtering, association rules, sentiment analysis, topic modeling, time-series analysis, regression, statistical inference, and validation methods.\nProficient in Deep Learning models and it applications in Natural Language Processing (NLP) and Computer Vision(CV) in solving business problems\nImplement algorithms and software needed to perform analyses\nCommunicate results and educate others through reports and presentations.',
 "WHAT WE NEED\nPh.D. or Masters or Bachelor's in computer science, Electrical / Computer Engineering\nOperations Research, Industrial Engineering or Mathematics / Statistics\n3- 5 years of relevant working experience\nProficient in RDBMS such as PostgresQL or MySQL.\nExpertise in Python along with expertise in (either one or both) Tensorflow/Pytorch.\nPractical experience in creating large scale recommender systems would be a huge plus (but is not a mandatory requirement)\nExperience in training Transformers from scratch would be a huge plus (but is not mandatory requirement).\nPrior experience of working with Variational Autoencoders would be a huge plus (but is not a mandatory requirement)\nDeep understanding of statistical and predictive modelling concepts\nStrong understanding of the practical applications of machine-learning approaches around supervised and unsupervised learning tasks.\nExperience in building ML models at scale, using real-time big data pipelines on platforms such as Spark/MapReduce.\nFamiliar with noSQL, postGIS, stream processing and distributed computing platforms\nWorking knowledge of Big Data technologies such as Hadoop, MPP Databases, or stream processing techniques.\nExperience working independently and, in a team,\nSelf-motivated, independent learner, and willing to share knowledge with team members\nDetail-oriented and efficient time manager in a dynamic and fast-paced working environment",
 'Role: Data Scientist\n\nRoles and Responsibilities\nSuitable candidates will be part of Wipro Digital-Intelligent Enterprise practice. The role entails leveraging Data Science and Machine Learning to solve typical problems within an organization and create IP that could be deployed in a productized mode. This will entail significant hands-on work on multiple Big Data Technologies, Data Analysis, Identifying data patterns, ML models, Insights generation. The role entails deployment in a customer context and managing customer expectations.\n\nTechnical Skills Required:\nHands on with Python or R\nAnalytics using industry leading BI tools and technologies\nImplementation knowledge of supervised\\un-supervised machine learning algorithms\nGood statistical analysis skills for data pre-processing and data wrangling\nExperienced in using big data frameworks like Hadoop\nKnowledge of business intelligence tools or reporting tools\n\nData Preparation for Modeling\nMissing Data Imputation,Outlier Treatment\nScaling, Normalization, Standardization\nEncoding for Categorical Variables\nOversampling\\Undersampling for reducing class imbalance\n\nExperience in building solutions using Model Library\nFeature Selection\nTree-based Ensemble Models\nGradient\\Adaptive Boosted Trees\nHyper-parameter tuning\nBuilding Prediction mechanisms using methods like Logistic regression, voting classifier stacking etc',
 'Responsibilities and Key Result Areas\nDesign and develop project prototypes and solutions.\nParticipate in project estimation, planning and risk management activities\nIs responsible for delivering input in the planning process to the project leader\nEnsures that there is proper documentation for the developed solutions.\nEnsure compliance to the Quality Management System and regulatory requirements\nKey Technical Skills:\n4 - 7 yrs years of experience in data science\nDeveloped Proficient in algorithms on regression modelling (linear/logistic), supervised and unsupervised classification,\ntree-based techniques (Decision trees /Random forest), neural nets, bagging, Pattern Mining and boosting techniques, etc.\nProficient and hands on experience in developing models using concepts of Artificial Intelligence,\nMachine Learning and Deep Learning related technologies (such as Keras, TensorFlow, pyTorch, Azure ML, AWS ML, Scikit, Jupyter, MatLab etc.)\nExperience with containers like Docker is added advantage\nExperience in Sql\nWorking experience in agile/SAFe development methodologies\nSoft Skill set:\nFast learner. Ability to grasp key concepts quickly with minimal or no supervision\nGo-Getter Attitude. Ability to take ownership of team goals and deliver it with quality and within required timeline\nTeam Player attitude. Key characteristic of the individual who puts the team first before self.\nAbility to think out of box: Ability to come up with bright ideas and always looking at the next big thing in technology\nFlexible and willingness to stretch oneself when needed.',
 'no description',
 'We are seeking an outstanding Lead Data Scientist in AI/ML who will help our team continue to grow and bring high value to Intel. In this role you should demonstrate excellent problem formulation/definition skills in addition to technical skills. The ideal candidate should be:\n\nA professional role model with deep and wide expertise in state-of-the-art AI/ML techniques, a passion for solving challenging data science problems and extensive hands-on experience.\nBe detail-oriented and have an aptitude for solving unstructured problems. You should be excellent in coming up with different approaches to solve business problem using AI and evaluate the trade-off between them.\nBe self-directed, take charge of opportunities with business impact and drive them to completion.\nHave prior experience in guiding a team of data scientists, coaching and mentoring them.\nHave deep technical expertise in feature-engineering of massive datasets, effective exploratory data analysis, and model building using AI/ML techniques.\nBe a role model innovator by adapting new AI/ML modeling techniques and procedures.\nHave deep expertise in creation and management of datasets.\nHave excellent business and communication skills to be able to work with stakeholders like the business teams, engineering teams and partner teams and align them with respect to your focus area.\nHave the ability to manage and execute an entire AI project from start to finish, including problem solving, data gathering and manipulation, predictive modeling, and project management skills.\nBe a role-model in storytelling with data and articulating the AI problems in an understandable manner to senior leadership of the Business Units.\n\nYou will be a part of the large global AI/ML Research Scientist community and will have access to state-of-the-art training, tools, and methods of the domain.\n\n\nCandidates need to hold at least a masters degree (or higher) in Computer Science/Machine Learning/AI/Data Science\n8 years of relevant experience in building AI/ML models and in using Python (Scikit-learn, TensorFlow/Pytorch) and SQL (or equivalent).\nExperience in using data analysis techniques and ML methods like classification, regression pattern finding, clustering, dimensionality reduction, anomaly detection etc.\nExperience with Hadoop, Spark is an advantage\nDeep Knowledge of classical AI algorithms and Deep Learning techniques is a must.\nGreat analytical skills and demonstrated ability of independent and creative thinking.\nHighly motivated strong team player with the ability to work both independently and collaboratively within a team.\nHas strong analytical skills, including the abilities to scope out business problems to be solved, start from ambiguous problem statements, identify and access relevant data, make appropriate assumptions, perform insightful analysis and draw conclusions relevant to the business problem.\nAbility to present information professionally and concisely with supporting data.\nPrevious experience as a data scientist in semi-conductor industry or data intensive organizations is a plus.\nExperience in creating powerful data driven visualizations to describe ML modeling results to stakeholders.',
 'no description',
 'Business & Team overview:\nFounded in 1987, Huawei is a leading global provider of ICT (information and communications technology) infrastructure and smart devices. We are committed to bringing digital to every person, home and organization for a fully connected, intelligent world. We have nearly 194,000 employees, and we operate in more than 170 countries and regions, serving more than 3 billion people around the world.\n\nHuawei Technologies has three business directions: Carrier Business Group, which provides innovative and secure network equipment to telecom carriers, including the leading 5G mobile network.\nEnterprise Business Group, which provides facilities and solutions to big and small companies, including IT facilities.\nConsumer Business Groups, which provides devices to the customer, including mobile phones, PC, tablet, TV, audio, glasses, watches, locomotives, and headphones. And also provide solutions on mobile offices, smart homes, sports and health, audio-visual entertainment, and smart travel products.\n\nThis opportunity is belong to Huawei Consumer Business Group.\n\nDriven by the coordinated development of "Chip-Device-Cloud", consumer products such as smartphones are becoming increasingly intelligent and pervasive. The era of smart services is the future.\n\nHuawei Ads Services is dedicated to provide Huawei end-users with high-quality digital experiences, to build a business closed-loop system for Developers and Improve the ROI for the Advertisers\n.\nIn 2020 Q1, along with more than 650 million users and 1,400,000 registered developers worldwide, we have the following unique advantages:\n1. With All-scenario intelligent solution, the Huawei devices become super entrance of traffic, including mobile phones, PC, tablet, TV, audio, glasses, watches, locomotives, and head phones\n2. This team will be responsible for building a new Ad Serving Platform and have the opportunity to define the product for our Huawei end-users.\n3. AI-Driven is the direction of Ads, Huawei is going to build a strong team in India to Innovate and deliver AI-driven Smart Ad Serving Platforms\n\nJob Title: Lead Data Scientist\nWe are looking for a Lead data scientist who will help us discover the information hidden in vast amounts of Ad Campaign data, and help us to optimize the campaign to improve the advertiser ROI and improve the overall consumer experience. Your primary focus will be in applying data mining techniques, doing statistical analysis, and building high quality prediction systems using Deep learning algorithms integrated with our products. Some the key area you will be working on spend recommendation, floor price prediction, CTR/CVR prediction, market funnel analysis and perdition of lead to conversion, etc.\n\nResponsibility:\nAnalyze the data, develop insights and identify the opportunity to utilize the data to predict various Advertisement key indicators like CTR, CVR, Inventory and Develop prediction and optimization algorithms for campaign, look alike modeling, etc for Huawei Ads.\nTakeup key challenges in AI-driven Smart Ad Serving Platform and focus on research and developing leading AI algorithms and productionize for Huawei Ads.\nTakeup initiative in identifying the SOTA and finding key gaps in AI algorithms and develop a world leading AI algorithms for optimizing real-time Ad Serving engine. Identify and optimize the core modules such as Traffic Prediction, Optimization, Ad Targeting/Re-targeting, Ad Performance Optimization, Audience insights, Attribution, Bidding, re-ranking, and Diagnostics. Support hundreds of billions of ad requests per day, with efficiently cache technology.\nTo build and enhance Ad platform features and Prediction capabilities in Huawei Ads Platform\nOptimized Cost Per Mille; Optimized Cost Per Action; Optimized Cost Per Click and Cost per Click. OCPM, OCPA, OCPC.\n\nRequirements:\n- Strong hands-on experience in implementing and validating big data algorithms and models including Deep Learning models like Seq2Seq/ GRU/RNN/LSTM , Knowledge Graph, Massive Graph algorithms, etc.\n- Programming experience with Python\n- Able to validate existing models including Deep Learning models with large scale dataset and able to make changes to the models to achieve better performance\n- AdServing domain Experience is an added advantage',

In [62]:
le=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
le[0:10]

[<selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="9d8b7a0e-c459-4f42-a61d-96db978dac21")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="1dabb5be-c852-433e-8cdd-843915dae1d3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="ca7382fe-5268-457f-9d39-244a8a08d387")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="1840981d-1008-49f3-bd19-80eb22740a0e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="f77b9719-8dd2-4794-aa21-ddf3027d7f28")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="ed064c90-1850-4a2e-af4c-d01efbbe2e3b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="32fb74b8-61c6-4753-a356-2b3d36a48e2e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="76b40e9c-50b7-4d28-ac72-51f99b655391")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="6350997f-7084-4218-a728-f6b98de6b8bd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="280e320a0bab618180cb6c4c3d06f8e9", element="8dccae21-3aa5-444f-8e0c-98d4b5068f33")>]

In [63]:
for i in le:
    ex=i.text
    job_location.append(ex)

job_location[0:10]

['Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram, Chennai, Bangalore/Bengaluru',
 'Noida, Chandigarh, Indore, Gurgaon/Gurugram, Ahmedabad, Jaipur, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)',
 'Noida, Chandigarh, Indore, Gurgaon/Gurugram, Ahmedabad, Jaipur, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)',
 'Noida, Gurgaon/Gurugram, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Kolkata, Hyderabad/Secunderabad, Chennai, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru']

In [65]:
d=pd.DataFrame({"job":job[0:5],
                "location":job_location[0:5],
                "company":company[0:5],
                "description":description[0:5]})

In [66]:
d

,job,location,company,description
0,Data Scientist / Data Analyst -Business Analyst,"Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/...",Inflexion Analytix Private Limited,Job Role : Data Scientist/Data Analyst /Busine...
1,Data Scientist,"Noida, Chandigarh, Indore, Gurgaon/Gurugram, A...",Wipro Limited,Roles and Responsibilities\nWe have Urgent Req...
2,Big Data - Data Scientist,"Noida, Chandigarh, Indore, Gurgaon/Gurugram, A...",Xoriant Solutions Pvt Ltd,Roles and Responsibilities\nWe have Urgent Req...
3,Specialist I - Data Scientist,"Noida, Gurgaon/Gurugram, Bangalore/Bengaluru",Philips India Limited,2-4 yrs - Job Location - Bangalore only\n\n4-6...
4,Lead Data Scientist,Bangalore/Bengaluru,Intel Technology India Pvt Ltd,WHAT WE NEED\nPh.D. or Masters or Bachelor's i...

In [67]:
driver.close()


# Q3: In this question you have to scrape data using the filters available on the webpage as shown below

You have to use the location and salary filter. You have to scrape data for “Data Scientist” designation for first 10 job results.

In [68]:
driver=webdriver.Chrome(r'C:\Users\Prsi\Desktop\ML\chromedriver.exe')

In [73]:
driver.get("https://www.naukri.com/data-scientist-jobs?k=data%20scientist&cityTypeGid=97&ctcFilter=3to6")

In [74]:
job=[]
company=[]
location=[]
experience=[]

In [75]:
title=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
title[0:10]

[<selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="356a780b-286f-4b9a-b19d-d41e2f73a2a7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="e970e626-ca0a-40b3-b76a-6c5a2e83720e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="de3dffa3-0c9b-4bd3-9a11-580ba1ba41ab")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="65421663-91eb-413c-ab81-6e87675d9317")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="67fd4960-4202-4261-80dc-cf96a86789a1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="9fe80f4a-3679-48e6-95a5-fac1eafb400d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="d2cfeaa7-53f8-477d-831c-03a00610a201")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="48727bdd-512e-4383-885a-65cb7d46aad1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="a9e012ae-8b51-4ba4-86d9-e8e1a9937b2a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="01bf0647-6c5f-42e3-88b1-1b1547e3d4d6")>]

In [76]:
for i in title:
    t=i.text
    job.append(t)
    
job[0:10]

['Data Scientist / Data Analyst -Business Analyst',
 'Data Scientist',
 'Data Scientist',
 'Big Data - Data Scientist',
 'Data Scientist',
 'we are hiring For the role of data engineer\\data scientist',
 'Sr Data Scientist, Payments',
 'Data Scientist - High growth VC backed Influencer Marketplace',
 'Data Scientist',
 'Data Scientist']

In [77]:
companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
companies_tags[0:10]

[<selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="2efaba27-f501-4c30-81f2-d3f303041a8e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="55b9cb3e-4fe4-4b09-9492-02f14814e0f1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="b62dc608-6a61-46a6-bdea-b2a74855ee8d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="27897689-84e5-48c3-ad1f-f33f6209445e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="5cae1b03-abbe-4022-820f-98d51df00afb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="5a238eea-1358-4ec3-9afc-762430af7890")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="a70a3e51-027d-49a4-93ab-6e536d7b6a73")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="38670251-669e-455d-9720-a5b2b947768c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="52886b82-9222-44b5-86d2-43033be4679e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="f6592bf2-bb0f-4a5c-8c12-49e78dff71cf")>]

In [78]:
for i in companies_tags:
    company_name=i.text
    company.append(company_name)

company[0:10]

['Inflexion Analytix Private Limited',
 'Wipro Limited',
 'IBM India Pvt. Limited',
 'Xoriant Solutions Pvt Ltd',
 'Applied Materials',
 'COLLABERA',
 'AIRBNB GLOBAL CAPABILITY CENTER PRIVATE LIMITED',
 'Ravgins International Pvt. Ltd.',
 'Glance IT Solution',
 'Walmart Labs']

In [79]:

e=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span[1]")
e[0:10]

[<selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="96a32c35-7dce-4d06-89cc-4a0e954e0ff1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="6a4659f7-e270-4273-9d89-c2df75e05b0f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="39250261-980c-49d0-bd01-457e599a2e2d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="b65ab20a-eee6-4315-8380-591b5b020580")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="dcbd9397-0f42-42bf-a82a-70d71920869a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="0911bbdd-459e-4605-ab0c-6aecea66b46f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="8e95b735-720e-4270-9e2d-97bc9b17bb73")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="dd9782c7-d255-4542-b3e7-1379bc994b9c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="69427b07-fbf1-480f-8b4b-04c794de8852")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="42fa90e7-4703-466b-ae11-773b75079b81")>]

In [80]:
for i in e:
    ex=i.text
    experience.append(ex)

experience[0:10]

['0-3 Yrs',
 '4-9 Yrs',
 '4-9 Yrs',
 '1-3 Yrs',
 '2-4 Yrs',
 '5-8 Yrs',
 '4-9 Yrs',
 '3-5 Yrs',
 '3-6 Yrs',
 '3-6 Yrs']

In [81]:
l=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
l[0:10]

[<selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="a96d8c0b-00d9-4b95-937d-96975ced3b2e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="52920941-c68a-4a25-8403-d7acdb8ecd8e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="d9e25544-4d03-438d-b024-692fbb3d93fb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="61b61d7f-2fd2-4036-ac62-59c64e987bc5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="4798ea1b-f1a4-4d6e-aacb-e715013e4d22")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="ec0d7582-ef60-40a9-a86c-47dc537540e5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="2a81bec5-0213-4615-b967-f19eaafecaaf")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="3add436c-4181-478f-8a3a-de2d6a01a2ad")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="f3d653f6-ec25-451c-8846-cdead1581ed5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="fbc00f38ad2286ab27769df7189e1166", element="e99483ee-2268-40f5-ac9f-8984625b0b03")>]

In [82]:
for i in l:
    ex=i.text
    location.append(ex)

location[0:10]

['Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram, Chennai, Bangalore/Bengaluru',
 'Kolkata, Hyderabad/Secunderabad, Chennai, Bangalore/Bengaluru',
 'Noida, Hyderabad/Secunderabad, Bangalore/Bengaluru',
 'Kochi/Cochin, Indore, Hyderabad/Secunderabad, Pune, Ahmedabad, Bangalore/Bengaluru, Mumbai (All Areas)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru']

In [83]:
df=pd.DataFrame({"job":job[0:10],
                "location":location[0:10],
                "company":company[0:10],
                "experience":experience[0:10]})

In [84]:
df

,job,location,company,experience
0,Data Scientist / Data Analyst -Business Analyst,"Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/...",Inflexion Analytix Private Limited,0-3 Yrs
1,Data Scientist,"Kolkata, Hyderabad/Secunderabad, Chennai, Bang...",Wipro Limited,4-9 Yrs
2,Data Scientist,"Noida, Hyderabad/Secunderabad, Bangalore/Benga...",IBM India Pvt. Limited,4-9 Yrs
3,Big Data - Data Scientist,"Kochi/Cochin, Indore, Hyderabad/Secunderabad, ...",Xoriant Solutions Pvt Ltd,1-3 Yrs
4,Data Scientist,Bangalore/Bengaluru,Applied Materials,2-4 Yrs
5,we are hiring For the role of data engineer\da...,Bangalore/Bengaluru,COLLABERA,5-8 Yrs
6,"Sr Data Scientist, Payments",Bangalore/Bengaluru,AIRBNB GLOBAL CAPABILITY CENTER PRIVATE LIMITED,4-9 Yrs
7,Data Scientist - High growth VC backed Influen...,"Bangalore/Bengaluru, Delhi / NCR, Mumbai (All ...",Ravgins International Pvt. Ltd.,3-5 Yrs
8,Data Scientist,Bangalore/Bengaluru,Glance IT Solution,3-6 Yrs
9,Data Scientist,Bangalore/Bengaluru,Walmart Labs,3-6 Yrs

In [85]:
driver.close()

# Q4: Write a python program to scrape data for first 10 job results for Data scientist Designation in Noida location. You have to scrape company_name, No. of days ago when job was posted, Rating of the company.

In [119]:
# to add timer
import time

# to use the keyborad keys
from selenium.webdriver.common.keys import Keys

# to remove pop ups
from selenium.webdriver.common.alert import Alert

# exceptions handling
from selenium.common.exceptions import NoSuchElementException

In [123]:
driver=webdriver.Chrome(r'C:\Users\Prsi\Desktop\ML\chromedriver.exe')

In [124]:
# open the glassdoor url in driver
url="https://www.glassdoor.co.in/index.htm"
driver.get(url)

# add timer to give driver time to load the webpage
time.sleep(2)

# get sign-in button web element
sign_in_btn=driver.find_element_by_xpath("//button[@class='d-none d-lg-block p-0 LockedHomeHeaderStyles__signInButton']")
# click on the sign-in button
sign_in_btn.click()


# get web-element for username bar
user_name=driver.find_element_by_id('userEmail')
# write the username
user_name.send_keys("ashish7@sharklasers.com")
# get web-element for password bar:
password=driver.find_element_by_id('userPassword')
# write the password
password.send_keys("8208507760")
# get webelement for sign-in button
sign=driver.find_element_by_xpath("//button[@class='gd-ui-button minWidthBtn css-8i7bc2']")
# click on the sign button
sign.click()



# add timer to give driver time to load the webpage
time.sleep(2)


# get the web-element for job search bar
job_search=driver.find_element_by_id('sc.keyword')
# enter the 'Data Scientist' text onto search bar
job_search.send_keys("Data Scientist")
#get the web-element for location search bar
loc_search=driver.find_element_by_id('sc.location')
# delete the existing text from location search bar
loc_search.send_keys(Keys.CONTROL+'a',Keys.BACKSPACE)
# enter the 'Noida' in location search bar
loc_search.send_keys("Noida")
# get webelement for 'search' button
search_btn=driver.find_element_by_xpath("//button[@data-test='search-bar-submit']")
# clicking the search button
search_btn.click()

# add timer to give driver time to load the webpage
time.sleep(2)

# get job titles info
# get job title tags
title_tag=driver.find_elements_by_xpath("//a[@class='jobLink css-1rd3saf eigr9kq2']")
# crete job titles list and initiate it
titles=[]
titles.clear()
for i in title_tag:
    titles.append(i.text)
    if len(titles)==10:
        break

#get company info
#get company name tags
comp_tag=driver.find_elements_by_xpath("//div[@class='d-flex justify-content-between align-items-start']")
#create companies list and initiate it
companies=[]
companies.clear()
for i in comp_tag:
    companies.append(i.text)
    if len(companies)==10:
        break

    
# get the location info
# get the location tags
loc_tag=driver.find_elements_by_xpath("//div[@class='d-flex flex-wrap css-11d3uq0 e1rrn5ka2']//span")
#create the loction list and initiate it
locations=[]
locations.clear()
for i in loc_tag:
    locations.append(i.text)
    if len(locations)==10:
        break

    
descriptions=[]
descriptions.clear()


for i in range(0,len(titles)):
    #storing the webelement for [i]th job description
    temp_tag=title_tag[i]
    
    if i==1:
    #getting webelement of Activate button of pop up of email notifications
        activ_btn=driver.find_element_by_xpath("//button[@class='gd-ui-button  e8e8plt0 css-1kp7eb7']")
    #click on activate button
        activ_btn.click()
    #getting webelement of 'x' close
        close_btn=driver.find_element_by_xpath("//span[@class='SVGInline modal_closeIcon']")
    # clicking on the close
        close_btn.click()
    
    #clicking on the [i]th job description
    temp_tag.click()
    
    # get webelement for job description
    descr_tag=driver.find_element_by_xpath("//div[@class='jobDescriptionContent desc']")
    # get text from above tag and append it to job description list
    descriptions.append(descr_tag.text.replace("\n"," "))

# add timer to give driver time to load the webpage
time.sleep(2)

driver.quit()

jobs_2=pd.DataFrame({})    
#enter data into dataframe
jobs_2['titles']=titles
jobs_2['company']=companies
jobs_2['Location']=locations
jobs_2['Job Description']=descriptions

In [125]:
jobs_2

,titles,company,Location,Job Description
0,Data Analyst,"Midland Credit Management, Inc.",Gurgaon,About Us We are more than a specialty finance ...
1,"Sr Manager - Data Science, AI, ML, R, Python, ...",UnitedHealth Group,Noida,Combine two of the fastest-growing fields on t...
2,Data Scientist,Ericsson,Noida,As the tech firm that created the mobile world...
3,Data Scientist,,Noida,Qualifications Masters in Computer Science/Mat...
4,Data Scientist,Boston Consulting Group,New Delhi,Location: New Delhi Geography: Asia Pacific Ca...
5,Data Scientist,Biz2Credit Inc,Noida,Job Description About the Role: This is a rare...
6,Data Scientist,Sparkbpl,Noida,Designation: Data Scientist ( 4 position) Loca...
7,Data Scientist,Mansha Solutions,Noida,About Profile We have an urgent opening for th...
8,Data Scientist,Priority Vendor,Noida,Data Sciences team at Priority Vendor uses dat...
9,Data Scientist,MasterCard,Gurgaon,Integrated Analytics has pioneered a transacti...

# Q5: Write a python program to scrape the salary data for Data Scientist designation in Noida location. You have to scrape Company name, Number of salaries, Average salary, Min salary, Max Salary.¶

In [129]:
driver=webdriver.Chrome(r'C:\Users\Prsi\Desktop\ML\chromedriver.exe')

In [130]:
# maximize
driver.maximize_window()

# open the glassdoor url in driver
url="https://www.glassdoor.co.in/Salaries/index.htm"
driver.get(url)

# get sign-in button web element
sign_in_btn=driver.find_element_by_xpath("//button[@class='d-none d-lg-block p-0 LockedHomeHeaderStyles__signInButton']")
# click on the sign-in button
sign_in_btn.click()


# get web-element for username bar
user_name=driver.find_element_by_id('userEmail')
# write the username
user_name.send_keys("ashish7@sharklasers.com")
# get web-element for password bar:
password=driver.find_element_by_id('userPassword')
# write the password
password.send_keys("8208507760")
# get webelement for sign-in button
sign=driver.find_element_by_xpath("//button[@class='gd-ui-button minWidthBtn css-8i7bc2']")
# click on the sign button
sign.click()

# add timer to give driver time to load the webpage
time.sleep(2)

#get the job search bar webelement
job_search=driver.find_element_by_xpath("//input[@name='sc.keyword']")
# write the text into search bar
job_search.send_keys("Data Scientist")

# get the location search bar web-element
loc_search=driver.find_element_by_id("LocationSearch")
# remove the existing text
loc_search.send_keys(Keys.CONTROL+'a',Keys.BACKSPACE)
# write the text into location search bar
loc_search.send_keys("Noida")

# get webelement for search button
search_btn=driver.find_element_by_xpath("//button[@id='HeroSearchButton']")
# click on the search button
search_btn.click()

# add timer to give driver time to load the webpage
time.sleep(2)

# get web element for job comp name
comp_wbe=driver.find_elements_by_xpath("//div[@data-test='job-info']")
# get text from above webelements
comps=[]
comps.clear()
temp_comps=[]
temp_comps.clear()
for i in comp_wbe:
    temp_comps.append(i.text)
    if len(temp_comps)==10:
        break
        
for i in temp_comps:
    comps.append(i.replace("\n",',').split(',')[1])

# get min max salary webelement
minmax_wbe=driver.find_elements_by_xpath("//div[@class='common__RangeBarStyle__rangeBar undefined undefined ']")
#get text from above webelement
sal_range=[]
sal_range.clear()
for i in minmax_wbe:
    sal_range.append(i.text)
    if len(sal_range)==10:
        break

min_sal=[]
max_sal=[]
min_sal.clear()
max_sal.clear()
for i in sal_range:
    min_sal.append(i.replace("\n"," ").split(" ")[0])
    max_sal.append(i.replace("\n"," ").split(" ")[1])

    
    
#get webelement for average salary
avg_sal_wbe=driver.find_elements_by_xpath("//div[@class='col-2 d-none d-md-flex flex-row justify-content-end']")
# get text from above
avg_sal=[]
avg_sal.clear()
for i in avg_sal_wbe:
    avg_sal.append(i.text)
    if len(avg_sal)==10:
        break

avg_sal_1=[]
avg_sal_1.clear()
for i in avg_sal:
    avg_sal_1.append(i.replace("\n"," "))

#driver.quit()

# create dataframe
job_4=pd.DataFrame({})
job_4['Companies']=comps
job_4['Min Salary']=min_sal
job_4['Max Salary']=max_sal
job_4['Average Salary']=avg_sal_1

In [131]:
job_4

                   Companies Min Salary Max Salary   Average Salary
0  Tata Consultancy Services      ₹343K    ₹1,250K   ₹ 6,14,306 /yr
1                  Accenture      ₹577K    ₹2,213K  ₹ 11,46,533 /yr
2                        IBM      ₹586K    ₹2,730K   ₹ 8,97,795 /yr
3         Ericsson-Worldwide      ₹355K    ₹1,613K   ₹ 7,38,057 /yr
4                  Delhivery      ₹450K   ₹11,622K  ₹ 12,39,781 /yr
5         UnitedHealth Group    ₹1,069K    ₹1,520K  ₹ 13,36,142 /yr
6         Valiance Solutions      ₹502K    ₹1,465K   ₹ 8,15,192 /yr
7              ZS Associates      ₹202K    ₹1,809K  ₹ 11,35,221 /yr
8                EXL Service      ₹575K    ₹1,520K  ₹ 11,44,243 /yr
9     Optum Global Solutions    ₹1,014K    ₹2,149K  ₹ 14,13,288 /yr

In [132]:
driver.close()

# Q6 : Scrape data of first 100 sunglasses listings on flipkart.com. You have to scrape four attributes: 1. Brand 2. Product Description 3. Price 4. Discount %

In [133]:
driver=webdriver.Chrome(r'C:\Users\Prsi\Desktop\ML\chromedriver.exe')

In [134]:
def fetch_data():
    # get web element for brand name
    brand_wbe=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
    #get brand name text
    for i in brand_wbe:
        brands.append(i.text)
        if len(brands)==100:
            break
        
    # get web element for Price
    price_wbe=driver.find_elements_by_xpath("//div[@class='_30jeq3']")
    # get price text from above
    for i in price_wbe:
        prices.append(i.text)
        if len(prices)==100:
            break

    #get web element for discount
    disc_wbe=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']")
    # get text from above
    for i in disc_wbe:
        discounts.append(i.text)
        if len(discounts)==100:
            break

    #get web element for product description
    descr_wbe=driver.find_elements_by_xpath("//a[@class='IRpwTa']")
    # get text from above
    for i in descr_wbe:
        descriptions.append(i.text)
        if len(descriptions)==100:
            break

In [135]:
# enter the url
url="https://www.flipkart.com/"
driver.get(url)

#add timer sleep
time.sleep(2)

# get web element for login email search bar
email_wbe=driver.find_element_by_xpath("//input[contains(@class,'_2IX_2-')]")#@class='_2IX_2- _2LYh3d VJZDxU'
# enter the email id
email_wbe.send_keys("8208507760")

#get web element for password bar
pwd_wbe=driver.find_element_by_xpath("//input[@type='password']")#class='_2IX_2- _3mctLh VJZDxU'
# enter the password
pwd_wbe.send_keys("Newpassword@72")

# get the webelement for login button
login_btn=driver.find_element_by_xpath("//button[@class='_2KpZ6l _2HKlqd _3AWRsL']")
#click on login button
login_btn.click()

#add timer sleep
time.sleep(3)

# get the web element for search bar
search_wbe=driver.find_element_by_xpath("//input[@name='q' and @placeholder='Search for products, brands and more']")
# write into search bar and pressing ENTER 
search_wbe.send_keys("sunglasses",Keys.ENTER)

#add timer sleep
time.sleep(3)


brands=[]
brands.clear()
        
prices=[]
prices.clear()

discounts=[]
discounts.clear()

descriptions=[]
descriptions.clear()

# get web element for page button
page_wbe=driver.find_elements_by_xpath("//a[contains(@class,'ge-49M')]")
# get urls of each page
page_urls=[]
page_urls.clear()

#to store page numbers
page_numbers=[]
page_numbers.clear()

# get urls of each next page from webelement
for i in page_wbe:
    temp_url= i.get_attribute('href') # getting the page urls
    page_urls.append(temp_url)        # storing the urls in a list
    page_numbers.append(i.text)
    
# counter for iteration    
counter=0   
# iterate over the webpages
for url in page_urls:
    if counter==0: # if 1st page, 
        fetch_data()
        counter=1 # change counter value to go to next webpage in next iteration
    else:
        if len(brands)==100: # checking if 100 items are scraped till this point during iterations
            break
        else:
            # store main window handle in a variable
            main_window=driver.current_window_handle
            
            # create a new tab to open the url
            driver.execute_script("window.open('about:blank','secondtab');")
            
            # switch driver to new tab
            driver.switch_to.window('secondtab')
            
            # open the new url in new tab
            driver.get(url)
            
            # give time to load webpage
            time.sleep(3)
            
            # fetch data from current page
            fetch_data()
            
            # close the new tab
            driver.close()
            
            # switch driver to main page
            driver.switch_to.window(main_window)


#close the driver
driver.quit()

# create the dataframe
glasses=pd.DataFrame({})
glasses['Brand Name']=brands
glasses['Price']=prices
glasses['Discount']=discounts
glasses['Product Description']=descriptions

In [136]:
glasses

,Brand Name,Price,Discount,Product Description
0,Fastrack,₹570,28% off,UV Protection Rectangular Sunglasses (Free Size)
1,ROZZETTA CRAFT,₹499,77% off,UV Protection Retro Square Sunglasses (Free Size)
2,PIRASO,₹349,78% off,UV Protection Aviator Sunglasses (Free Size)
3,ROYAL SON,₹265,79% off,UV Protection Wayfarer Sunglasses (55)
4,DEIXELS,₹209,73% off,UV Protection Round Sunglasses (Free Size)
...,...,...,...,...
95,Fastrack,₹758,15% off,UV Protection Wayfarer Sunglasses (Free Size)
96,ROYAL SON,₹664,66% off,"Polarized, UV Protection Aviator Sunglasses (F..."
97,ROZZETTA CRAFT,₹449,77% off,"UV Protection, Polarized Wayfarer Sunglasses (56)"
98,Fastrack,₹759,15% off,UV Protection Aviator Sunglasses (Free Size)
99,Fastrack,₹759,15% off,UV Protection Wayfarer Sunglasses (Free Size)

# Q.7 Scrape 100 reviews data from flipkart.com for iphone11 phone.

In [137]:
def fetch_data():
    # get webelement for rating
    rate_wbe=driver.find_elements_by_xpath("//div[contains(@class,'_3LWZlK _')]")
    #get text from above
    for i in rate_wbe:
        ratings.append(i.text)

    # get web element for short review
    short_wbe=driver.find_elements_by_xpath("//div[@class='row']//p[@class='_2-N8zT']")
    # get text from above
    for i in short_wbe:
        short_rev.append(i.text)

    # get wbe for full review
    full_wbe=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']//div[@class='row']//div[@class='t-ZTKy']")
    # get text from above
    for i in full_wbe:
        full_rev.append(i.text.replace("\n"," "))

In [138]:
driver=webdriver.Chrome(r'C:\Users\Prsi\Desktop\ML\chromedriver.exe')

In [139]:
# lets enter the url
url="https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace"
driver.get(url)

#add timer
time.sleep(3)

# get web element for all reviews link
all_reviews_wbe=driver.find_element_by_xpath("//div[@class='_3UAT2v _16PBlm']")
# click on above wbe
all_reviews_wbe.click()


#add time
time.sleep(3)

# get web element for page button
page_wbe=driver.find_elements_by_xpath("//a[contains(@class,'ge-49M')]")
# get urls of each page
page_urls=[]
page_urls.clear()

page_numbers=[]
page_numbers.clear()

for i in page_wbe: # get webpage web-elements
    temp_url= i.get_attribute('href') # get webpage urls
    page_urls.append(temp_url) # store urls
    page_numbers.append(i.text)


ratings=[]
ratings.clear()

short_rev=[]
short_rev.clear()

full_rev=[]
full_rev.clear()    
    
# counter to keep track of pages    
counter=0   
for url in page_urls: # iterate over the webpages
    if counter==0: # if 1st page
        fetch_data()
        counter=1 # incrementing the counter to go next webpage in next iteration
    else:
        # store main page window handle
        main_window=driver.current_window_handle
        
        # open a new tab
        driver.execute_script("window.open('about:blank','secondtab');")
        
        # switch driver to new tab
        driver.switch_to.window('secondtab')
        
        # open the new webpage in new tab
        driver.get(url)
        
        # give time to load
        time.sleep(3)
        
        # fetch data from current webpage
        fetch_data()
        
        #close the new tab
        driver.close()
        
        # switch to main window
        driver.switch_to.window(main_window)
            
# create dataframe
reviews=pd.DataFrame({})
reviews['Iphone-11 Rating']=ratings
reviews['Short Review']=short_rev
reviews['Full Review']=full_rev

reviews

,Iphone-11 Rating,Short Review,Full Review
0,5,Brilliant,The Best Phone for the Money The iPhone 11 of...
1,5,Perfect product!,Amazing phone with great cameras and better ba...
2,5,Great product,Amazing Powerful and Durable Gadget. I’m am v...
3,5,Worth every penny,Previously I was using one plus 3t it was a gr...
4,4,Good choice,So far it’s been an AMAZING experience coming ...
...,...,...,...
95,5,Best in the market!,The best all rounder iphone. Flipkart is doing...
96,5,Terrific,I upgraded (downgraded?) from my iPhone X sinc...
97,5,Terrific purchase,"Well , as we all know if its not an Iphone , i..."
98,5,Wonderful,Nice value for money good and best price I pho...
99,5,Fabulous!,Just an awesome phone...upgraded from 6s to 11...

In [140]:
driver.close()

# Q.8 Scrape data for first 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the search field.

In [141]:
def fetch_data():
    # get web element for brand name
    brand_wbe=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
    #get brand name text
    for i in brand_wbe:
        brands.append(i.text)
        if len(brands)==100:
            break
        
    # get web element for Price
    price_wbe=driver.find_elements_by_xpath("//div[@class='_30jeq3']")
    # get price text from above
    for i in price_wbe:
        prices.append(i.text)
        if len(prices)==100:
            break

    #get web element for discount
    disc_wbe=driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']")
    # get text from above
    for i in disc_wbe:
        discounts.append(i.text)
        if len(discounts)==100:
            break

    #get web element for product description
    descr_wbe=driver.find_elements_by_xpath("//a[contains(@class,'IRpwTa')]")
    # get text from above
    for i in descr_wbe:
        descriptions.append(i.text)
        if len(descriptions)==100:
            break

In [142]:
driver=webdriver.Chrome(r'C:\Users\Prsi\Desktop\ML\chromedriver.exe')

In [143]:
# enter the url
url="https://www.flipkart.com/"
driver.get(url)

#add timer sleep
time.sleep(2)

# get web element for login email search bar
email_wbe=driver.find_element_by_xpath("//input[contains(@class,'_2IX_2-')]")#@class='_2IX_2- _2LYh3d VJZDxU'
# enter the email id
email_wbe.send_keys("8208507760")

#get web element for password bar
pwd_wbe=driver.find_element_by_xpath("//input[@type='password']")#class='_2IX_2- _3mctLh VJZDxU'
# enter the password
pwd_wbe.send_keys("Newpassword@72")

# get the webelement for login button
login_btn=driver.find_element_by_xpath("//button[@class='_2KpZ6l _2HKlqd _3AWRsL']")
#click on login button
login_btn.click()

#add timer sleep
time.sleep(3)

# get the web element for search bar
search_wbe=driver.find_element_by_xpath("//input[@name='q' and @placeholder='Search for products, brands and more']")
# write into search bar and pressing ENTER 
search_wbe.send_keys("sneakers",Keys.ENTER)

#add timer sleep
time.sleep(3)


brands=[]
brands.clear()
        
prices=[]
prices.clear()

discounts=[]
discounts.clear()

descriptions=[]
descriptions.clear()

# get web element for page button
page_wbe=driver.find_elements_by_xpath("//a[contains(@class,'ge-49M')]")
# get urls of each page
page_urls=[]
page_urls.clear()

#to store page numbers
page_numbers=[]
page_numbers.clear()

# get urls of each next page from webelement
for i in page_wbe:
    temp_url= i.get_attribute('href')
    page_urls.append(temp_url)
    page_numbers.append(i.text)
    
    
counter=0   
for url in page_urls: # iterate over page urls
    if counter==0: # if 1st page
        fetch_data()
        counter=1 # increment counter to advance to next page in next iteration
    else:
        if len(brands)==100: # check if 100 items are scraped till now
            break
        else:
            # get main page window handle
            main_window=driver.current_window_handle
            
            #open a new tab
            driver.execute_script("window.open('about:blank','secondtab');")
            
            # switch to new tab
            driver.switch_to.window('secondtab')
            
            # open new url in new tab
            driver.get(url)
            
            # give time to load the webpage
            time.sleep(3)
            
            # scrape data from current webpage
            fetch_data()
            
            # close the new tab
            driver.close()
            
            # switch to main page
            driver.switch_to.window(main_window)


#close the driver
#driver.quit()

# create the dataframe
sneakers=pd.DataFrame({})
sneakers['Brand Name']=brands
sneakers['Price']=prices
sneakers['Discount']=discounts
sneakers['Product Description']=descriptions

In [144]:
sneakers

,Brand Name,Price,Discount,Product Description
0,DUCATI,"₹1,924",47% off,Sneakers For Men
1,DUCATI,"₹1,199",67% off,Sneakers For Men
2,Robbie jones,₹379,62% off,Casual Sneakers Shoes For Men Sneakers For Men
3,Robbie jones,₹474,52% off,Sneakers For Men
4,HOTSTYLE,₹283,43% off,Sneakers Sneakers For Men
...,...,...,...,...
95,bluemaker,₹449,36% off,casual for men (black 08) Sneakers For Men
96,PUMA,"₹1,549",59% off,Speeder DP Sneakers For Men
97,LEATHERKRAFT,₹299,48% off,Sneakers For Men
98,City Soles,₹630,8% off,Cipramo Canvas Shoes for Men Sneakers For Men
99,DUCATI,"₹1,461",70% off,Sneakers For Men

In [145]:
driver.close()

# Q.9 - Scraping myntra website for black shoes with price filtering

In [146]:
def fetch_data():
    # get webelement for brand name
    brand_wbe=driver.find_elements_by_xpath("//div[@class='product-productMetaInfo']/h3")
    #get text
    for i in brand_wbe:
        brands.append(i.text)
        if len(brands)==100:
            break
    
        
    #get webelement for product description
    descr_wbe=driver.find_elements_by_xpath("//div[@class='product-productMetaInfo']/h4[@class='product-product']")
    # get text
    for i in descr_wbe:
        descriptions.append(i.text)
        if len(descriptions)==100:
            break
    
    #get webelement for price
    price_wbe=driver.find_elements_by_xpath("//div[@class='product-price']/span[1]")
    #get text
    for i in price_wbe:
        if len(prices)==100:
            break
        else:
            temp_text=i.text
            if len(temp_text)<9:
                prices.append(temp_text)
            else:
                temp_text2=temp_text.split('Rs. ')[1]
                prices.append("Rs. "+temp_text2)

In [147]:
driver=webdriver.Chrome(r'C:\Users\Prsi\Desktop\ML\chromedriver.exe')

In [151]:
driver.get('https://www.myntra.com/shoes?f=Color%3ABlack_36454f&rf=Price%3A6649.0_13099.0_6649.0%20TO%2013099.0%2C6337.0_10225.0_6337.0%20TO%2010225.0')

In [154]:
start_page=0
end_page=0
for page in range(start_page,end_page+1): 
    nxt_button=driver.find_element_by_xpath("//li[@class='pagination-next']")
    
    #creating empty lists
    shoe_names=[]
    s_desc=[]
    short_desc=[]
    price=[]
    
    #for scrapping shoe brand names
    Names=driver.find_elements_by_xpath("//div[@class='product-productMetaInfo']/h3")
    for i in Names:
        shoe_names.append(i.text)
    
    #for scrapping shoe short-description
    desc=driver.find_elements_by_xpath("//div[@class='product-productMetaInfo']/h4")
    for i in desc:
        s_desc.append(i.text)
    #As, the s_desc list contain blank description in every alternate index, so removing the blank or null description
    for j in range(0,len(s_desc),2):
        short_desc.append(s_desc[j])
    
    #for scrapping shoe prices
    desc=driver.find_elements_by_xpath("//div[@class='product-price']")
    for i in desc:
        price.append(i.text)
    
    #for scrapping the datas from next pages.
    if nxt_button.text=='next':
            nxt_button.click()
            time.sleep(5)
    
    # create the dataframe
shoes=pd.DataFrame({})
shoes['Brand Name']=shoe_names
shoes['Price']=price
shoes['Product Description']=short_desc 

shoes

,Brand Name,Price,Product Description
0,ALDO,Rs. 9999,Men Sneakers
1,Nike,Rs. 12995,Men KD13 EP Basketball Shoes
2,ALDO,Rs. 6499Rs. 12999(50% OFF),Men Textured Leather Loafers
3,Nike,Rs. 11246Rs. 14995(25% OFF),Men JOYRIDE Running Shoes
4,Nike,Rs. 7721Rs. 10295(25% OFF),Men AIR ZOOM Running Shoes
5,Nike,Rs. 12495,Men JORDAN DELTA Basketball
6,Puma,Rs. 7199Rs. 7999(10% OFF),Men FUTURE Z 3.1Football Shoes
7,PUMA Motorsport,Rs. 7999,Unisex Mercedes Running Shoes
8,Nike,Rs. 6636Rs. 8295(20% OFF),Women REACT ESCAPE Running
9,Nike,Rs. 7496Rs. 9995(25% OFF),Women PEGASUS 37 Running Shoes
10,Nike,Rs. 11621Rs. 15495(25% OFF),Men React Infinity Running
11,Nike,Rs. 11495,AIR ZOOM PEGASUS Running Shoes
12,Nike,Rs. 8996Rs. 11995(25% OFF),Women REACT Running Shoes
13,Nike,Rs. 6396Rs. 7995(20% OFF),Men AIR MAX EXCEE Sneakers
14,Puma,Rs. 7649Rs. 8999(15% OFF),Men UltraRide Running Shoes
15,Puma,Rs. 6399Rs. 7999(20% OFF),Men Mesh Fuse Training Or Gym Shoes
16,UNDER ARMOUR,Rs. 10999,Men Liquify Running Shoes
17,Puma,Rs. 10999,Men Velocity Nitro Running
18,Puma,Rs. 6999Rs. 9999(30% OFF),Men SPEED 500 2 Running Shoes
19,Puma,Rs. 9999,Unisex RS-FAST TECH Sneakers
20,UNDER ARMOUR,Rs. 7999,Charged Rogue 2 Wide 2E Shoes
21,UNDER ARMOUR,Rs. 10999,HOVR Sonic 3 Running Shoes
22,Puma,Rs. 12999,Women Eternity Nitro Running
23,ROSSO BRUNELLO,Rs. 10799Rs. 11999(10% OFF),Men Solid Leather Formal Slip-Ons
24,Hush Puppies,Rs. 8999,Men Solid Leather Formal Slip-Ons
25,ADIDAS,Rs. 6499Rs. 9999(35% OFF),Men ALPHATORSION Running Shoes
26,Puma,Rs. 6374Rs. 7499(15% OFF),Men FUTURE Z 3.1 TT Football
27,UNDER ARMOUR,Rs. 7999,Charged Impulse Running Shoes
28,Puma,Rs. 6499,Unisex Ralph Sampson Sneakers
29,UNDER ARMOUR,Rs. 11999,HOVR Infinite 2 Running Shoes
30,ADIDAS Originals,Rs. 8449Rs. 12999(35% OFF),Men Nite Jogger Fluid Sneakers
31,ROSSO BRUNELLO,Rs. 10349Rs. 11499(10% OFF),Men Solid Monk Shoes
32,Puma,Rs. 7999,Women Provoke XT Training
33,Puma,Rs. 7999Rs. 9999(20% OFF),Women Liberate Nitro Running
34,FILA,Rs. 8499,Men Running Shoes
35,UNDER ARMOUR,Rs. 8999,Women Liquify Rebel Running
36,Skechers,Rs. 6999,Women D'LITES 3.0 Sneakers
37,Onitsuka Tiger,Rs. 6999,Unisex Mexico 66 Paraty Sneakers
38,UNDER ARMOUR,Rs. 7999,Women Charged Breathe TR 2
39,ROSSO BRUNELLO,Rs. 10799Rs. 11999(10% OFF),Men Solid Leather Formal Oxfords
40,Nike,Rs. 10995,Men JORDAN DELTA Sneakers
41,UNDER ARMOUR,Rs. 8999,Women Charged Breathe OIL SLK
42,Skechers,Rs. 7999,Women UNO Sneakers
43,Hush Puppies,Rs. 9999,Men Formal Derbys
44,Ruosh,Rs. 8990,Men Solid Leather Formal Derbys
45,Heel & Buckle London,Rs. 7693Rs. 10990(30% OFF),Men Leather Formal Oxfords
46,Puma,Rs. 6999,Future Rider Twofold Sneakers
47,ROSSO BRUNELLO,Rs. 10799Rs. 11999(10% OFF),Men Solid Leather Formal Loafers
48,Puma,Rs. 8499Rs. 9999(15% OFF),Unisex RS-X Pop Sneakers
49,Ruosh,Rs. 6990,Men Leather Formal Brogues

In [155]:
driver.close()

# Q10: Go to webpage https://www.amazon.in/Enter “Laptop” in the search field and then click the search icon.Then set CPU Type filter to “Intel Core i7” and “Intel Core i9” After setting the filters scrape first 10 laptops data.You have to scrape 3 attributes for each laptop:

In [156]:
driver=webdriver.Chrome(r'C:\Users\Prsi\Desktop\ML\chromedriver.exe')

In [160]:
# enter the url
url='https://www.amazon.in/'
driver.get(url)

#add timer
time.sleep(3)

driver.maximize_window()

# get the webelement for search bar
search_wbe=driver.find_element_by_xpath("//input[@type='text' and @id='twotabsearchtextbox']")
#enter into search bar
search_wbe.send_keys("Laptop",Keys.ENTER)


#add timer
time.sleep(3)

# get webelement of 1st filter
i7_wbe=driver.find_element_by_xpath("//li[@id='p_n_feature_thirteen_browse-bin/12598163031']//following::i")
#click
i7_wbe.click()

# get webelement for title
title_wbe=driver.find_elements_by_xpath("//span[@class='a-size-medium a-color-base a-text-normal']")
titles=[]
titles.clear()
for i in title_wbe:
    titles.append(i.text)
    if len(titles)==10:
        break
        
        
ratings=[]
ratings.clear()
prices=[]
prices.clear()

for wbe in title_wbe:    
    #click on the title
    wbe.click()
    
    #add timer
    time.sleep(3)

    #swtich to new window
    driver.switch_to.window(driver.window_handles[1])
    
    #add timer
    time.sleep(3)
    
    # get webelement for rating
    try:
        rating_wbe=driver.find_element_by_xpath("//div[@class='a-section a-spacing-none a-spacing-top-mini cr-widget-ACR']")
        # get rating text
        if rating_wbe.text=='':
            ratings.append("Not Available")
        else:
            ratings.append(rating_wbe.text.replace("\n",",").split(",")[0])
    except NoSuchElementException:
        ratings.append("Not Available")
        
    #add timer
    time.sleep(3)
    
    # get webelement for price
    try:
        price_wbe=driver.find_element_by_xpath("//span[@id='priceblock_ourprice']")
        #get price text
        prices.append(price_wbe.text)
    except NoSuchElementException:
        try:
            price_wbe=driver.find_element_by_xpath("//span[@id='priceblock_dealprice']")
            #get price text
            prices.append(price_wbe.text+"(Deal Price)")
        except NoSuchElementException:
            prices.append("Not Available")
    
    
    # close the new window
    driver.close()
    
    #switch to main window
    driver.switch_to.window(driver.window_handles[0])
    
    if len(prices)==10:
        break

        
# create dataframes
lp_models=pd.DataFrame({})
lp_models['CPU type']=pd.Series(['Intel core i7' for x in range(len(titles))])
lp_models['Model']=titles
lp_models['Rating']=ratings
lp_models['Price']=prices


#get webelement for clear filter
clear_wbe=driver.find_element_by_xpath("//li[@class='a-spacing-micro s-list-item']//following::a")
# clear the 1st filter
clear_wbe.click()
#add timer
time.sleep(3)

# get webelement for 2nd filter
i9_wbe=driver.find_element_by_xpath("//li[@id='p_n_feature_thirteen_browse-bin/16757432031']//following::i")
#click
i9_wbe.click()

#add timer
time.sleep(3)

# get webelement for title
title_wbe_1=driver.find_elements_by_xpath("//span[@class='a-size-medium a-color-base a-text-normal']")
titles_1=[]
titles_1.clear()
for i in title_wbe_1:
    titles_1.append(i.text)
    if len(titles_1)==10:
        break
        
        
ratings_1=[]
ratings_1.clear()
prices_1=[]
prices_1.clear()

for wbe in title_wbe_1:    
    #click on the title
    wbe.click()
    
    #add timer
    time.sleep(3)

    #swtich to new window
    driver.switch_to.window(driver.window_handles[1])
    
    #add timer
    time.sleep(3)
    
    # get webelement for rating
    try:
        rating_wbe_1=driver.find_element_by_xpath("//div[@class='a-section a-spacing-none a-spacing-top-mini cr-widget-ACR']")
        # get rating text
        if (rating_wbe_1.text=='' or rating_wbe_1.text=='None'):
            ratings_1.append("Not Available")
        else:
            ratings_1.append(rating_wbe_1.text.replace("\n",",").split(",")[0])
    except NoSuchElementException:
        ratings_1.append("Not Available")
        
    #add timer
    time.sleep(3)
    
    # get webelement for price
    try:
        price_wbe_1=driver.find_element_by_xpath("//span[@id='priceblock_ourprice']")
        #get price text
        prices_1.append(price_wbe_1.text)
    except NoSuchElementException:
        try:
            price_wbe_1=driver.find_element_by_xpath("//span[@id='priceblock_dealprice']")
            #get price text
            prices_1.append(price_wbe_1.text+"(Deal Price)")
        except NoSuchElementException:
            prices_1.append("Not Available")
    
    
    # close the new window
    driver.close()
    
    #switch to main window
    driver.switch_to.window(driver.window_handles[0])
    
    if len(prices_1)==10:
        break


# create dataframes
lp_models_1=pd.DataFrame({})
lp_models_1['CPU type']=pd.Series(['Intel core i9' for x in range(len(titles_1))])
lp_models_1['Model']=titles_1
lp_models_1['Rating']=ratings_1
lp_models_1['Price']=prices_1

lp_models.append(lp_models_1,ignore_index=True)

,CPU type,Model,Rating,Price
0,Intel core i7,ASUS ZenBook 14 (2020) Intel Core i7-1165G7 11...,4.4 out of 5,"₹ 96,990.00"
1,Intel core i7,"ASUS ZenBook Flip S OLED, Intel Evo Core i7-11...",4.6 out of 5,"₹ 1,49,990.00"
2,Intel core i7,Mi Notebook Horizon Edition 14 Intel Core i5-1...,4.4 out of 5,"₹ 49,999.00(Deal Price)"
3,Intel core i7,"Lenovo Legion 5Pi 10th Gen Intel Core i7 15.6""...",4.3 out of 5,Not Available
4,Intel core i7,Life Digital Laptop 15.6-inch (39.62 cms) (Int...,2.9 out of 5,"₹ 47,050.00"
5,Intel core i7,HP Pavilion (2021) Thin & Light 11th Gen Core ...,4.4 out of 5,"₹ 84,999.00"
6,Intel core i7,(Renewed) HP EliteBook 840 G3 Laptop (Core i7 ...,Not Available,"₹ 49,999.00"
7,Intel core i7,"Asus ROG Zephyrus S Ultra Slim Gaming Laptop, ...",4.3 out of 5,"₹ 3,43,099.00"
8,Intel core i7,(Renewed) Dell Intel 4th Gen Core i7 4600U 14-...,Not Available,"₹ 39,999.00"
9,Intel core i7,Lenovo IdeaPad Flex 5 11th Gen Intel Core i7 1...,4 out of 5,"₹ 83,990.00"
10,Intel core i9,"ASUS ROG Zephyrus Duo 15, 15.6"" FHD 300Hz/3ms,...",Not Available,"₹ 2,66,990.00"
11,Intel core i9,"ASUS ROG G703GI-E5148T 17.3"" (43.94 cms) FHD 1...",3.7 out of 5,"₹ 4,13,890.00(Deal Price)"
12,Intel core i9,ASUS ZenBook Pro Duo Intel Core i9-10980HK 10t...,3.8 out of 5,"₹ 2,99,325.00"
13,Intel core i9,"Dell XPS 9570 15.6"" (39.62cms) UHD Laptop (8th...",2.4 out of 5,"₹ 2,48,790.00"
14,Intel core i9,Lenovo Legion 7 10th Gen Intel Core i9 15.6 in...,3.7 out of 5,"₹ 2,62,990.00"
15,Intel core i9,ASUS ZenBook Pro Duo UX581GV-H2041T Intel Core...,3.9 out of 5,"₹ 2,79,990.00"
16,Intel core i9,"ASUS ROG Strix Scar 15 (2020), 15.6"" FHD 300Hz...",4.2 out of 5,"₹ 2,15,990.00"
17,Intel core i9,"ASUS ROG Strix Scar 17 (2020), 17.3"" FHD 300Hz...",4.8 out of 5,"₹ 2,77,639.00"
18,Intel core i9,(Renewed) Dell XPS 9570 Laptop|i9-8950HK|32GB ...,Not Available,Not Available
19,Intel core i9,Dell G7 7500 15.6inch FHD 300 Hz Display Gamin...,3.4 out of 5,"₹ 2,00,690.00"